#!/bin/bash
#
# Script to control (start, stop, restart, save, watch, ...) a Minecraft server
#

# Default settings
SERVER_IP="127.0.0.1"
PATH_START_SCRIPT="/mnt/ramdisk/minecraft/start.sh"
PATH_LOG="/mnt/ramdisk/minecraft/server.log"
RCON_PASSWORD=""
RCON_PORT=25575
MCRCON_PATH="mcrcon"
QUIETE=0
FILTER=""

# Print usage
usage() {
    echo "Usage: mc-control [-opts] [cmd]"
    echo
    echo "Options:"
    echo "  -h       Display this message"
    echo "  -s       Specify a non-default server IP"
    echo "  -p       Specify a non-default rcon password"
    echo "  -q       Don't output any status messages"
    echo "  -f       Filter logs"
    echo
    echo "Commands:"
    echo "  start    Start the server"
    echo "  status   Check wether the server is up or not"
    echo "  restart  Restart the server"
    echo "  stop     Stop the server"
    echo "  save     Send save-all command to the server"
    echo "  watch    Watch the server's live log"
    echo "  tps      Watch the server's live Tick-per-second stats on 1-second interval"
    echo "  list     Fetch online users"
    echo "  rcon     Open an rcon console"
    echo
    echo "Example:"
    echo "  mc-control watch -s 85.12.6.48 -p p@ssw0rd -f 'logged in with'"
    echo "  mc-control start"
    echo "  mc-control stop -q"

    exit 1
}

log() {
    if [ $QUIETE -eq 0 ]; then
        echo -ne "$1"
    fi
}

check_online() {
    if [[ "$( $MCRCON_PATH -H $SERVER_IP -P $RCON_PORT -p $RCON_PASSWORD list 2>&1 )" == *"online"* ]]; then
        echo 1
    else
        echo 0
    fi
}

rcon_command() {
    $( $MCRCON_PATH -H $SERVER_IP -P $RCON_PORT -p $RCON_PASSWORD $1 2>&1 )
}

rcon_output() {
    echo $( $MCRCON_PATH -H $SERVER_IP -P $RCON_PORT -p $RCON_PASSWORD $1 )
}

# Process arguments
while [ $# -gt 0 ];
do
    case "$1"
    in
        -h|--help|--usage) usage;;
        -s|--server)
            SERVER_IP=$2
            shift
        ;;
        -p|--password)
            RCON_PASSWORD=$2
            shift
        ;;
        -q|--quiete) QUIETE=1;;
        -f|--filter)
            FILTER=$2
            shift
        ;;
        start|status|restart|stop|save|watch|tps|list|rcon) ACTION=$1;;
        *)
            echo "Unknown option: $1"
            echo
            usage
        ;;
    esac
    shift
done

# Process action
case "$ACTION"
in
    start)
        # Start the server
        log " * Checking if the server is down."

        # Check wether the server isn't running already
        if [ $( check_online ) -eq 0 ]; then
            log " OK\n"
            log " * Starting the server."

            # Run the start script
            su - minecraft -c "screen -d -S minecraft -m sh $PATH_START_SCRIPT"

            # Wait till the server comes up
            while [ $( check_online ) -eq 0 ]; do
                log "."
                sleep 1
            done
            log " OK\n"
        else
            log " FAIL\n"
        fi
        ;;
    status)
        if [ $( check_online ) -eq 1 ]; then
            log "The server is reachable and responding.\n"
        else
            log "Could not poll the server - it could be down or unresponsive.\n"
        fi
        ;;
    restart)
        # Check if the server is reachable
        if [ $( check_online ) -eq 0 ]; then
            if [ $( "ps aux|grep java|wc -l" ) -ge 2 ]; then
                if [ $QUIETE -eq 0 ]; then
                    log "The server is running but is unreachable or doesn't respond.\n"
                    read -p "Do you want to force kill and restart the server [y/N]?"
                    if [ $REPLY -eq "y" ]; then
                        log " * Killing all java instances... "
                        killall -9 java
                        log "OK\n"
                    else
                        exit 1
                    fi
                else
                    exit 1
                fi
            else
                log " * Server seems to be stopped.\n"
            fi
        else
            log " * Stopping the server."

            # Stop the server
            rcon_command "stop"

            # Wait till the server is down
            while [ $( check_online ) -eq 1 ]; do
                log "."
                sleep 1
            done

            sleep 5 #Just in case
            log " OK\n"
        fi

        # Start the server
        log " * Starting the server."

        # Run the start script
        su - minecraft -c "screen -d -S minecraft -m sh $PATH_START_SCRIPT"

        # Wait till the server comes up
        while [ $( check_online ) -eq 0 ]; do
            log "."
            sleep 1
        done
        log " OK\n"
        ;;
    stop)
        # Check if the server is reachable
        if [ $( check_online ) -eq 0 ]; then
            if [ $( "ps aux|grep java|wc -l" ) -ge 2 ]; then
                if [ $QUIETE -eq 0 ]; then
                    log "The server is running but is unreachable or doesn't respond.\n"
                    read -p "Do you want to force kill and restart the server [y/N]?"
                    if [ $REPLY -eq "y" ]; then
                        log " * Killing all java instances... "
                        killall -9 java
                        log "OK\n"
                    else
                        exit 1
                    fi
                else
                    exit 1
                fi
            else
                log " * Server seems to be stopped.\n"
            fi
        else
            log " * Stopping the server."

            # Stop the server
            rcon_command "stop"

            # Wait till the server is down
            while [ $( check_online ) -eq 1 ]; do
                log "."
                sleep 1
            done

            sleep 5 #Just in case
            log " OK\n"
        fi
        ;;
    save)
        # Check if the server is online
        if [ $( check_online ) -eq 0 ]; then
            log "The server seems to be down.\n"
            exit 1
        fi

        # Send save command
        log " * Sending save command... "
        rcon_command "save-all"
        log "OK\n"
        ;;
    watch)
        # Check if the server log file exists
        if [ -f $PATH_LOG ]; then
            if [ $FILTER == "" ]; then
                # Tail the log
                tail -f $PATH_LOG
            else
                # Tail the log and pipe it through grep
                tail -f $PATH_LOG | grep "$FILTER"
            fi
        else
            log "$PATH_LOG: no such file or directory\n"
        fi
        ;;
    tps)
        # Check if the server is up
        if [ $( check_online ) -eq 0 ]; then
            log "The server seems to be down.\n"
            exit 1
        fi

        # Check TPS every 1 second
        log " * Fetching Ticks-per-second every 1 second.\n\n"
        while [ true ]; do
            log "[$( date -u )]: $( rcon_output tps )\n"
            sleep 1
        done
        ;;
    *)
        usage
        ;;
esac
